# Generated by Django 3.2.3 on 2021-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('face_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'face_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file_address', models.CharField(max_length=225)),
                ('user_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('group_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('rep_faceid', models.CharField(max_length=255)),
                ('rep_faceaddress', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_fileid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
